"""initial

Revision ID: 64289bd60156
Revises: 
Create Date: 2026-05-08 15:52:26.218551
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64289bd60156'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tandas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto_periodo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_periodo', sa.Enum('SEMANAL', 'QUINCENAL', 'MENSUAL', name='tipoperiodo'), nullable=False),
    sa.Column('numero_participantes', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACTIVA', 'COMPLETADA', 'CANCELADA', name='estadotanda'), nullable=False),
    sa.Column('orden_sorteado', sa.Boolean(), nullable=False),
    sa.Column('creador_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tanda_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tanda_id'], ['tandas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tanda_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=False),
    sa.Column('cobrador_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COBRADA', 'SALTADA', name='estadoronda'), nullable=False),
    sa.ForeignKeyConstraint(['cobrador_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['tanda_id'], ['tandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ronda_id', sa.UUID(), nullable=False),
    sa.Column('participante_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADO', 'ATRASADO', name='estadopago'), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['ronda_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('rounds')
    op.drop_table('participants')
    op.drop_table('tandas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
