"""add_fecha_fin

Revision ID: bc63a7d32eae
Revises: 96d27408e035
Create Date: 2026-05-08 16:31:28.621518
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc63a7d32eae'
down_revision: Union[str, None] = '96d27408e035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tandas', sa.Column('fecha_fin', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tandas', 'fecha_fin')
    # ### end Alembic commands ###
